version: "2"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  backend:
    build: ./backend-node/
    ports:
      - "6200:6200"
    volumes:
      - ./backend-node:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./frontend-react/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react:/usr/src/app
    depends_on:
      - backend
